name: Comment on a first pull request
on: 
  - pull_request
  - issues
 
permissions:
  pull-requests: write
  issues: write
 
jobs: # The jobs that run in this workflow
  greeting:
    runs-on: ubuntu-latest
    steps: # The "steps" section contains the individual tasks that will be performed in this job.
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            # Message with markdown
            Hienosti tehty ensimmäinen issue!
          pr-message: |
            Oho! Ensimmäinen pull request!
